### ISSUE TITLE
Can send message on multi channel.

### ISSUE THREAD

**Issue by FallenCrystal** [frafol/CleanStaffChat#5]
/dc
/ac
/sc

![image](https://github.com/frafol/CleanStaffChat/assets/71176602/20a94b9b-0d01-4d92-8b66-88394a4d9808)

**Comment by frafol** [comment]
Please try this build (unzip the archive)

[cleanstaffchat-1.9.2.zip](https://github.com/frafol/CleanStaffChat/files/11582024/cleanstaffchat-1.9.2.zip)

(tell me if it works)

**Comment by FallenCrystal** [comment]
> Please try this build (unzip the archive)
> 
> [cleanstaffchat-1.9.2.zip](https://github.com/frafol/CleanStaffChat/files/11582024/cleanstaffchat-1.9.2.zip)
> 
> (tell me if it works)

sorry for late.

yes. this jar fixed this issue
